// <auto-generated />
using System;
using DNDWiki.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DNDWiki.Migrations
{
    [DbContext(typeof(DNDDbContext))]
    [Migration("20260326034053_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbilityDndClass", b =>
                {
                    b.Property<int>("DndClassId")
                        .HasColumnType("int");

                    b.Property<int>("SavingThrowProficienciesId")
                        .HasColumnType("int");

                    b.HasKey("DndClassId", "SavingThrowProficienciesId");

                    b.HasIndex("SavingThrowProficienciesId");

                    b.ToTable("AbilityDndClass");
                });

            modelBuilder.Entity("ArmorTrainingDndClass", b =>
                {
                    b.Property<int>("ArmorProficienciesId")
                        .HasColumnType("int");

                    b.Property<int>("DndClassId")
                        .HasColumnType("int");

                    b.HasKey("ArmorProficienciesId", "DndClassId");

                    b.HasIndex("DndClassId");

                    b.ToTable("ArmorTrainingDndClass");
                });

            modelBuilder.Entity("CreatureSizeSpecies", b =>
                {
                    b.Property<int>("CreatureSizesId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("CreatureSizesId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("CreatureSizeSpecies");
                });

            modelBuilder.Entity("CreatureTypeSpecies", b =>
                {
                    b.Property<int>("CreatureTypesId")
                        .HasColumnType("int");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("CreatureTypesId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("CreatureTypeSpecies");
                });

            modelBuilder.Entity("DNDWiki.Models.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dexterity"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Constitution"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Intelligence"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wisdom"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Charisma"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.ArmorTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArmorTrainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Light"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Heavy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shields"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.ClassFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DndClassId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DndClassId");

                    b.ToTable("ClassFeature");
                });

            modelBuilder.Entity("DNDWiki.Models.CreatureSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CreatureSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tiny"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Small"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Large"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Huge"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gargantuan"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.CreatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CreatureTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aberration"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beast"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Celestial"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Construct"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Elemental"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fey"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fiend"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Giant"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Humanoid"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Monstrosity"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ooze"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Plant"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Undead"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.DndClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HitPointDie")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("DndClasses");
                });

            modelBuilder.Entity("DNDWiki.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("TypeId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Item").HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DNDWiki.Models.ItemFeatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemToolId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemToolId");

                    b.HasIndex("WeaponId");

                    b.ToTable("ItemFeatures");
                });

            modelBuilder.Entity("DNDWiki.Models.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemType");
                });

            modelBuilder.Entity("DNDWiki.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbilityId = 1,
                            Name = "Athletics"
                        },
                        new
                        {
                            Id = 2,
                            AbilityId = 2,
                            Name = "Acrobatics"
                        },
                        new
                        {
                            Id = 3,
                            AbilityId = 2,
                            Name = "SleightOfHand"
                        },
                        new
                        {
                            Id = 4,
                            AbilityId = 2,
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 5,
                            AbilityId = 4,
                            Name = "Arcana"
                        },
                        new
                        {
                            Id = 6,
                            AbilityId = 4,
                            Name = "History"
                        },
                        new
                        {
                            Id = 7,
                            AbilityId = 4,
                            Name = "Investigation"
                        },
                        new
                        {
                            Id = 8,
                            AbilityId = 4,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 9,
                            AbilityId = 4,
                            Name = "Religion"
                        },
                        new
                        {
                            Id = 10,
                            AbilityId = 5,
                            Name = "AnimalHandling"
                        },
                        new
                        {
                            Id = 11,
                            AbilityId = 5,
                            Name = "Insight"
                        },
                        new
                        {
                            Id = 12,
                            AbilityId = 5,
                            Name = "Medicine"
                        },
                        new
                        {
                            Id = 13,
                            AbilityId = 5,
                            Name = "Perception"
                        },
                        new
                        {
                            Id = 14,
                            AbilityId = 5,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 15,
                            AbilityId = 6,
                            Name = "Deception"
                        },
                        new
                        {
                            Id = 16,
                            AbilityId = 6,
                            Name = "Intimidation"
                        },
                        new
                        {
                            Id = 17,
                            AbilityId = 6,
                            Name = "Performance"
                        },
                        new
                        {
                            Id = 18,
                            AbilityId = 6,
                            Name = "Persuasion"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            Id = "PHB24",
                            Name = "Players Handbook 2024"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<string>("TypicalSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypicalWeight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("DNDWiki.Models.Spells", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasMaterialComponent")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSomaticComponent")
                        .HasColumnType("bit");

                    b.Property<bool>("HasVerbalComponent")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MaterialList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("School")
                        .HasColumnType("int");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("DNDWiki.Models.WeaponType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WeaponTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Simple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Martial"
                        });
                });

            modelBuilder.Entity("DndClassItemTool", b =>
                {
                    b.Property<int>("DndClassId")
                        .HasColumnType("int");

                    b.Property<int>("ToolsProficienciesId")
                        .HasColumnType("int");

                    b.HasKey("DndClassId", "ToolsProficienciesId");

                    b.HasIndex("ToolsProficienciesId");

                    b.ToTable("DndClassItemTool");
                });

            modelBuilder.Entity("DndClassSkill", b =>
                {
                    b.Property<int>("DndClassId")
                        .HasColumnType("int");

                    b.Property<int>("SkillProficienciesId")
                        .HasColumnType("int");

                    b.HasKey("DndClassId", "SkillProficienciesId");

                    b.HasIndex("SkillProficienciesId");

                    b.ToTable("DndClassSkill");
                });

            modelBuilder.Entity("DndClassSpells", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("int");

                    b.Property<int>("SpellsId")
                        .HasColumnType("int");

                    b.HasKey("ClassesId", "SpellsId");

                    b.HasIndex("SpellsId");

                    b.ToTable("DndClassSpells");
                });

            modelBuilder.Entity("DndClassWeaponType", b =>
                {
                    b.Property<int>("DndClassId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponsProficienciesId")
                        .HasColumnType("int");

                    b.HasKey("DndClassId", "WeaponsProficienciesId");

                    b.HasIndex("WeaponsProficienciesId");

                    b.ToTable("DndClassWeaponType");
                });

            modelBuilder.Entity("DNDWiki.Models.ItemTool", b =>
                {
                    b.HasBaseType("DNDWiki.Models.Item");

                    b.HasDiscriminator().HasValue("Tool");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "AlchemistSupplies"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "BrewersSupplies"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "CalligraphersSupplies"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "CarpentersTools"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "CartographersTools"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "CobblersTools"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "CooksUtensils"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            Name = "GlassblowersTools"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            Name = "JewelersTools"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            Name = "LeatherworkersTools"
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            Name = "MasonsTools"
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            Name = "PaintersSupplies"
                        },
                        new
                        {
                            Id = 13,
                            Description = "",
                            Name = "PottersTools"
                        },
                        new
                        {
                            Id = 14,
                            Description = "",
                            Name = "SmithsTools"
                        },
                        new
                        {
                            Id = 15,
                            Description = "",
                            Name = "TinkersTools"
                        },
                        new
                        {
                            Id = 16,
                            Description = "",
                            Name = "WeaversTools"
                        },
                        new
                        {
                            Id = 17,
                            Description = "",
                            Name = "WoodcarversTools"
                        },
                        new
                        {
                            Id = 18,
                            Description = "",
                            Name = "Bagpipes"
                        },
                        new
                        {
                            Id = 19,
                            Description = "",
                            Name = "Drum"
                        },
                        new
                        {
                            Id = 20,
                            Description = "",
                            Name = "Dulcimer"
                        },
                        new
                        {
                            Id = 21,
                            Description = "",
                            Name = "Flute"
                        },
                        new
                        {
                            Id = 22,
                            Description = "",
                            Name = "Lute"
                        },
                        new
                        {
                            Id = 23,
                            Description = "",
                            Name = "Lyre"
                        },
                        new
                        {
                            Id = 24,
                            Description = "",
                            Name = "Horn"
                        },
                        new
                        {
                            Id = 25,
                            Description = "",
                            Name = "PanFlute"
                        },
                        new
                        {
                            Id = 26,
                            Description = "",
                            Name = "Shawm"
                        },
                        new
                        {
                            Id = 27,
                            Description = "",
                            Name = "Viol"
                        },
                        new
                        {
                            Id = 28,
                            Description = "",
                            Name = "DisguiseKit"
                        },
                        new
                        {
                            Id = 29,
                            Description = "",
                            Name = "ForgeryKit"
                        },
                        new
                        {
                            Id = 30,
                            Description = "",
                            Name = "HerbalismKit"
                        },
                        new
                        {
                            Id = 31,
                            Description = "",
                            Name = "NavigatorsTools"
                        },
                        new
                        {
                            Id = 32,
                            Description = "",
                            Name = "PoisonersKit"
                        },
                        new
                        {
                            Id = 33,
                            Description = "",
                            Name = "ThievesTools"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.Weapon", b =>
                {
                    b.HasBaseType("DNDWiki.Models.Item");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeaponTypeId")
                        .HasColumnType("int");

                    b.HasIndex("WeaponTypeId");

                    b.HasDiscriminator().HasValue("Weapon");
                });

            modelBuilder.Entity("AbilityDndClass", b =>
                {
                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany()
                        .HasForeignKey("DndClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DNDWiki.Models.Ability", null)
                        .WithMany()
                        .HasForeignKey("SavingThrowProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArmorTrainingDndClass", b =>
                {
                    b.HasOne("DNDWiki.Models.ArmorTraining", null)
                        .WithMany()
                        .HasForeignKey("ArmorProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany()
                        .HasForeignKey("DndClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CreatureSizeSpecies", b =>
                {
                    b.HasOne("DNDWiki.Models.CreatureSize", null)
                        .WithMany()
                        .HasForeignKey("CreatureSizesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DNDWiki.Models.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CreatureTypeSpecies", b =>
                {
                    b.HasOne("DNDWiki.Models.CreatureType", null)
                        .WithMany()
                        .HasForeignKey("CreatureTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DNDWiki.Models.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DNDWiki.Models.ClassFeature", b =>
                {
                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany("ClassFeatures")
                        .HasForeignKey("DndClassId");
                });

            modelBuilder.Entity("DNDWiki.Models.DndClass", b =>
                {
                    b.HasOne("DNDWiki.Models.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("DNDWiki.Models.Item", b =>
                {
                    b.HasOne("DNDWiki.Models.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.HasOne("DNDWiki.Models.ItemType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.OwnsOne("DNDWiki.Models.Money", "Price", b1 =>
                        {
                            b1.Property<int>("ItemId")
                                .HasColumnType("int");

                            b1.Property<int>("CopperPieces")
                                .HasColumnType("int");

                            b1.Property<int>("GoldPieces")
                                .HasColumnType("int");

                            b1.Property<int>("PlatiniumPieces")
                                .HasColumnType("int");

                            b1.Property<int>("SilverPieces")
                                .HasColumnType("int");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Price");

                    b.Navigation("Source");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DNDWiki.Models.ItemFeatures", b =>
                {
                    b.HasOne("DNDWiki.Models.ItemTool", null)
                        .WithMany("Properties")
                        .HasForeignKey("ItemToolId");

                    b.HasOne("DNDWiki.Models.Weapon", null)
                        .WithMany("Properties")
                        .HasForeignKey("WeaponId");
                });

            modelBuilder.Entity("DNDWiki.Models.Skill", b =>
                {
                    b.HasOne("DNDWiki.Models.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("DNDWiki.Models.Species", b =>
                {
                    b.HasOne("DNDWiki.Models.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("DNDWiki.Models.CreatureTraits", "Traits", b1 =>
                        {
                            b1.Property<int>("SpeciesId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Level")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SpeciesId", "Id");

                            b1.ToTable("CreatureTraits");

                            b1.WithOwner()
                                .HasForeignKey("SpeciesId");
                        });

                    b.Navigation("Source");

                    b.Navigation("Traits");
                });

            modelBuilder.Entity("DNDWiki.Models.Spells", b =>
                {
                    b.HasOne("DNDWiki.Models.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DNDWiki.Models.TimeDnd", "CastingTime", b1 =>
                        {
                            b1.Property<int>("SpellsId")
                                .HasColumnType("int");

                            b1.Property<int>("Scale")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("SpellsId");

                            b1.ToTable("Spells");

                            b1.WithOwner()
                                .HasForeignKey("SpellsId");
                        });

                    b.OwnsOne("DNDWiki.Models.TimeDnd", "Duration", b1 =>
                        {
                            b1.Property<int>("SpellsId")
                                .HasColumnType("int");

                            b1.Property<int>("Scale")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("SpellsId");

                            b1.ToTable("Spells");

                            b1.WithOwner()
                                .HasForeignKey("SpellsId");
                        });

                    b.Navigation("CastingTime")
                        .IsRequired();

                    b.Navigation("Duration")
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("DndClassItemTool", b =>
                {
                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany()
                        .HasForeignKey("DndClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DNDWiki.Models.ItemTool", null)
                        .WithMany()
                        .HasForeignKey("ToolsProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndClassSkill", b =>
                {
                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany()
                        .HasForeignKey("DndClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DNDWiki.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndClassSpells", b =>
                {
                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DNDWiki.Models.Spells", null)
                        .WithMany()
                        .HasForeignKey("SpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DndClassWeaponType", b =>
                {
                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany()
                        .HasForeignKey("DndClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DNDWiki.Models.WeaponType", null)
                        .WithMany()
                        .HasForeignKey("WeaponsProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DNDWiki.Models.Weapon", b =>
                {
                    b.HasOne("DNDWiki.Models.ItemType", "WeaponType")
                        .WithMany()
                        .HasForeignKey("WeaponTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("DNDWiki.Models.DndClass", b =>
                {
                    b.Navigation("ClassFeatures");
                });

            modelBuilder.Entity("DNDWiki.Models.ItemTool", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("DNDWiki.Models.Weapon", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
