// <auto-generated />
using System;
using DNDWiki.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DNDWiki.Migrations
{
    [DbContext(typeof(DNDDbContext))]
    partial class DNDDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DNDWiki.Models.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DndClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DndClassId");

                    b.ToTable("Abilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dexterity"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Constitution"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Intelligence"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wisdom"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Charisma"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.ArmorTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DndClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DndClassId");

                    b.ToTable("ArmorTrainings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Light"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Heavy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shields"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.ClassFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DndClassId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DndClassId");

                    b.ToTable("ClassFeature");
                });

            modelBuilder.Entity("DNDWiki.Models.DndClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HitPointDie")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("DndClasses");
                });

            modelBuilder.Entity("DNDWiki.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.Property<int?>("DndClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("DndClassId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbilityId = 1,
                            Name = "Athletics"
                        },
                        new
                        {
                            Id = 2,
                            AbilityId = 2,
                            Name = "Acrobatics"
                        },
                        new
                        {
                            Id = 3,
                            AbilityId = 2,
                            Name = "SleightOfHand"
                        },
                        new
                        {
                            Id = 4,
                            AbilityId = 2,
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 5,
                            AbilityId = 4,
                            Name = "Arcana"
                        },
                        new
                        {
                            Id = 6,
                            AbilityId = 4,
                            Name = "History"
                        },
                        new
                        {
                            Id = 7,
                            AbilityId = 4,
                            Name = "Investigation"
                        },
                        new
                        {
                            Id = 8,
                            AbilityId = 4,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 9,
                            AbilityId = 4,
                            Name = "Religion"
                        },
                        new
                        {
                            Id = 10,
                            AbilityId = 5,
                            Name = "AnimalHandling"
                        },
                        new
                        {
                            Id = 11,
                            AbilityId = 5,
                            Name = "Insight"
                        },
                        new
                        {
                            Id = 12,
                            AbilityId = 5,
                            Name = "Medicine"
                        },
                        new
                        {
                            Id = 13,
                            AbilityId = 5,
                            Name = "Perception"
                        },
                        new
                        {
                            Id = 14,
                            AbilityId = 5,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 15,
                            AbilityId = 6,
                            Name = "Deception"
                        },
                        new
                        {
                            Id = 16,
                            AbilityId = 6,
                            Name = "Intimidation"
                        },
                        new
                        {
                            Id = 17,
                            AbilityId = 6,
                            Name = "Performance"
                        },
                        new
                        {
                            Id = 18,
                            AbilityId = 6,
                            Name = "Persuasion"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.Source", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            Id = "PHB24",
                            Name = "Players Handbook 2024"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.ToolType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DndClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DndClassId");

                    b.ToTable("ToolTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AlchemistSupplies"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BrewersSupplies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CalligraphersSupplies"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CarpentersTools"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CartographersTools"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CobblersTools"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CooksUtensils"
                        },
                        new
                        {
                            Id = 8,
                            Name = "GlassblowersTools"
                        },
                        new
                        {
                            Id = 9,
                            Name = "JewelersTools"
                        },
                        new
                        {
                            Id = 10,
                            Name = "LeatherworkersTools"
                        },
                        new
                        {
                            Id = 11,
                            Name = "MasonsTools"
                        },
                        new
                        {
                            Id = 12,
                            Name = "PaintersSupplies"
                        },
                        new
                        {
                            Id = 13,
                            Name = "PottersTools"
                        },
                        new
                        {
                            Id = 14,
                            Name = "SmithsTools"
                        },
                        new
                        {
                            Id = 15,
                            Name = "TinkersTools"
                        },
                        new
                        {
                            Id = 16,
                            Name = "WeaversTools"
                        },
                        new
                        {
                            Id = 17,
                            Name = "WoodcarversTools"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bagpipes"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Drum"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Dulcimer"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Flute"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Lute"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Lyre"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Horn"
                        },
                        new
                        {
                            Id = 25,
                            Name = "PanFlute"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Shawm"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Viol"
                        },
                        new
                        {
                            Id = 28,
                            Name = "DisguiseKit"
                        },
                        new
                        {
                            Id = 29,
                            Name = "ForgeryKit"
                        },
                        new
                        {
                            Id = 30,
                            Name = "HerbalismKit"
                        },
                        new
                        {
                            Id = 31,
                            Name = "NavigatorsTools"
                        },
                        new
                        {
                            Id = 32,
                            Name = "PoisonersKit"
                        },
                        new
                        {
                            Id = 33,
                            Name = "ThievesTools"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.WeaponType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DndClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DndClassId");

                    b.ToTable("WeaponTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Simple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Martial"
                        });
                });

            modelBuilder.Entity("DNDWiki.Models.Ability", b =>
                {
                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany("SavingThrowProficiencies")
                        .HasForeignKey("DndClassId");
                });

            modelBuilder.Entity("DNDWiki.Models.ArmorTraining", b =>
                {
                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany("ArmorProficiencies")
                        .HasForeignKey("DndClassId");
                });

            modelBuilder.Entity("DNDWiki.Models.ClassFeature", b =>
                {
                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany("ClassFeatures")
                        .HasForeignKey("DndClassId");
                });

            modelBuilder.Entity("DNDWiki.Models.DndClass", b =>
                {
                    b.HasOne("DNDWiki.Models.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("DNDWiki.Models.Skill", b =>
                {
                    b.HasOne("DNDWiki.Models.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany("SkillProficiencies")
                        .HasForeignKey("DndClassId");

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("DNDWiki.Models.ToolType", b =>
                {
                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany("ToolsProficiencies")
                        .HasForeignKey("DndClassId");
                });

            modelBuilder.Entity("DNDWiki.Models.WeaponType", b =>
                {
                    b.HasOne("DNDWiki.Models.DndClass", null)
                        .WithMany("WeaponsProficiencies")
                        .HasForeignKey("DndClassId");
                });

            modelBuilder.Entity("DNDWiki.Models.DndClass", b =>
                {
                    b.Navigation("ArmorProficiencies");

                    b.Navigation("ClassFeatures");

                    b.Navigation("SavingThrowProficiencies");

                    b.Navigation("SkillProficiencies");

                    b.Navigation("ToolsProficiencies");

                    b.Navigation("WeaponsProficiencies");
                });
#pragma warning restore 612, 618
        }
    }
}
